export interface CityData {
  name: string;
  slug: string;
  state: string;
  stateName: string;
  population: number;
  medianAge: number;
  medianIncome: number;
  retirementPct: number;
  majorEmployers: string[];
}

export const CITIES: CityData[] = [
  // Alabama
  {
    name: "Birmingham",
    slug: "birmingham",
    state: "alabama",
    stateName: "Alabama",
    population: 197575,
    medianAge: 36.8,
    medianIncome: 37120,
    retirementPct: 26.1,
    majorEmployers: ["UAB Health System", "Regions Financial", "AT&T", "Honda Manufacturing", "Vulcan Materials"],
  },
  // Alaska
  {
    name: "Anchorage",
    slug: "anchorage",
    state: "alaska",
    stateName: "Alaska",
    population: 291247,
    medianAge: 33.8,
    medianIncome: 76871,
    retirementPct: 22.3,
    majorEmployers: ["Providence Alaska Medical Center", "Joint Base Elmendorf-Richardson", "ConocoPhillips", "GCI", "Alaska Airlines"],
  },
  // Arizona
  {
    name: "Mesa",
    slug: "mesa",
    state: "arizona",
    stateName: "Arizona",
    population: 508958,
    medianAge: 37.2,
    medianIncome: 61100,
    retirementPct: 28.4,
    majorEmployers: ["Boeing", "Banner Health", "AT&T", "Mesa Public Schools", "Fender Musical Instruments"],
  },
  {
    name: "Phoenix",
    slug: "phoenix",
    state: "arizona",
    stateName: "Arizona",
    population: 1608139,
    medianAge: 34.5,
    medianIncome: 57459,
    retirementPct: 22.8,
    majorEmployers: ["Banner Health", "Honeywell", "American Express", "Wells Fargo", "Intel"],
  },
  {
    name: "Scottsdale",
    slug: "scottsdale",
    state: "arizona",
    stateName: "Arizona",
    population: 241361,
    medianAge: 47.4,
    medianIncome: 93040,
    retirementPct: 37.2,
    majorEmployers: ["Scottsdale Healthcare", "General Dynamics", "GoDaddy", "Vanguard", "JDA Software"],
  },
  {
    name: "Sedona",
    slug: "sedona",
    state: "arizona",
    stateName: "Arizona",
    population: 10336,
    medianAge: 57.3,
    medianIncome: 56780,
    retirementPct: 52.1,
    majorEmployers: ["Sedona Medical Center", "Enchantment Resort", "L'Auberge de Sedona", "City of Sedona", "Verde Valley Tourism"],
  },
  {
    name: "Sun City",
    slug: "sun-city",
    state: "arizona",
    stateName: "Arizona",
    population: 39504,
    medianAge: 72.8,
    medianIncome: 38950,
    retirementPct: 81.3,
    majorEmployers: ["Banner Boswell Medical Center", "Sun Health", "Recreation Centers of Sun City", "Del Webb", "Walmart"],
  },
  {
    name: "Tucson",
    slug: "tucson",
    state: "arizona",
    stateName: "Arizona",
    population: 542629,
    medianAge: 34.9,
    medianIncome: 43425,
    retirementPct: 25.6,
    majorEmployers: ["University of Arizona", "Raytheon", "Davis-Monthan AFB", "Banner Health", "Tucson Medical Center"],
  },
  // Arkansas
  {
    name: "Little Rock",
    slug: "little-rock",
    state: "arkansas",
    stateName: "Arkansas",
    population: 202591,
    medianAge: 36.4,
    medianIncome: 48520,
    retirementPct: 24.8,
    majorEmployers: ["UAMS Medical Center", "Dillard's", "Windstream Holdings", "Baptist Health", "Stephens Inc"],
  },
  // California
  {
    name: "Los Angeles",
    slug: "los-angeles",
    state: "california",
    stateName: "California",
    population: 3898747,
    medianAge: 36.2,
    medianIncome: 65290,
    retirementPct: 22.4,
    majorEmployers: ["Kaiser Permanente", "UCLA Health", "Northrop Grumman", "Walt Disney Company", "Cedars-Sinai"],
  },
  {
    name: "Palm Springs",
    slug: "palm-springs",
    state: "california",
    stateName: "California",
    population: 48390,
    medianAge: 52.6,
    medianIncome: 49820,
    retirementPct: 44.7,
    majorEmployers: ["Desert Regional Medical Center", "Agua Caliente Band of Cahuilla Indians", "Hyatt Regency", "City of Palm Springs", "Palm Springs Unified School District"],
  },
  {
    name: "Sacramento",
    slug: "sacramento",
    state: "california",
    stateName: "California",
    population: 524943,
    medianAge: 35.4,
    medianIncome: 62335,
    retirementPct: 23.1,
    majorEmployers: ["State of California", "UC Davis Health", "Kaiser Permanente", "Sutter Health", "Intel"],
  },
  {
    name: "San Diego",
    slug: "san-diego",
    state: "california",
    stateName: "California",
    population: 1386932,
    medianAge: 35.6,
    medianIncome: 79646,
    retirementPct: 23.8,
    majorEmployers: ["UC San Diego Health", "Qualcomm", "Northrop Grumman", "Sharp HealthCare", "General Atomics"],
  },
  {
    name: "San Francisco",
    slug: "san-francisco",
    state: "california",
    stateName: "California",
    population: 873965,
    medianAge: 38.2,
    medianIncome: 112449,
    retirementPct: 24.5,
    majorEmployers: ["Salesforce", "Wells Fargo", "UCSF Medical Center", "Gap Inc", "Charles Schwab"],
  },
  {
    name: "San Jose",
    slug: "san-jose",
    state: "california",
    stateName: "California",
    population: 1013240,
    medianAge: 37.0,
    medianIncome: 109593,
    retirementPct: 22.9,
    majorEmployers: ["Cisco Systems", "Adobe", "PayPal", "eBay", "Western Digital"],
  },
  // Colorado
  {
    name: "Colorado Springs",
    slug: "colorado-springs",
    state: "colorado",
    stateName: "Colorado",
    population: 478961,
    medianAge: 34.8,
    medianIncome: 63020,
    retirementPct: 24.2,
    majorEmployers: ["Fort Carson Army Base", "Lockheed Martin", "UCHealth", "US Air Force Academy", "Penrose-St. Francis Health"],
  },
  {
    name: "Denver",
    slug: "denver",
    state: "colorado",
    stateName: "Colorado",
    population: 715522,
    medianAge: 34.6,
    medianIncome: 72661,
    retirementPct: 21.3,
    majorEmployers: ["UCHealth", "Lockheed Martin", "DaVita", "Arrow Electronics", "Centura Health"],
  },
  // Connecticut
  {
    name: "Hartford",
    slug: "hartford",
    state: "connecticut",
    stateName: "Connecticut",
    population: 121054,
    medianAge: 31.7,
    medianIncome: 36154,
    retirementPct: 22.5,
    majorEmployers: ["Hartford HealthCare", "The Hartford", "Aetna", "United Technologies", "Cigna"],
  },
  // Delaware
  {
    name: "Wilmington",
    slug: "wilmington",
    state: "delaware",
    stateName: "Delaware",
    population: 70635,
    medianAge: 34.5,
    medianIncome: 44580,
    retirementPct: 25.9,
    majorEmployers: ["JPMorgan Chase", "Bank of America", "Christiana Care Health", "DuPont", "AstraZeneca"],
  },
  // Florida
  {
    name: "Boca Raton",
    slug: "boca-raton",
    state: "florida",
    stateName: "Florida",
    population: 99805,
    medianAge: 47.2,
    medianIncome: 72105,
    retirementPct: 39.8,
    majorEmployers: ["Florida Atlantic University", "Boca Raton Regional Hospital", "ADT", "Office Depot", "Bluegreen Vacations"],
  },
  {
    name: "Clearwater",
    slug: "clearwater",
    state: "florida",
    stateName: "Florida",
    population: 117580,
    medianAge: 45.2,
    medianIncome: 47021,
    retirementPct: 35.8,
    majorEmployers: ["BayCare Health System", "Scientology Church HQ", "Honeywell", "Tech Data", "City of Clearwater"],
  },
  {
    name: "Fort Lauderdale",
    slug: "fort-lauderdale",
    state: "florida",
    stateName: "Florida",
    population: 182760,
    medianAge: 42.5,
    medianIncome: 55288,
    retirementPct: 30.2,
    majorEmployers: ["Broward Health", "AutoNation", "Citrix Systems", "Spirit Airlines", "National Beverage Corp"],
  },
  {
    name: "Jacksonville",
    slug: "jacksonville",
    state: "florida",
    stateName: "Florida",
    population: 949611,
    medianAge: 36.4,
    medianIncome: 54701,
    retirementPct: 24.7,
    majorEmployers: ["Mayo Clinic", "Naval Air Station Jacksonville", "Baptist Health", "CSX Transportation", "Florida Blue"],
  },
  {
    name: "Miami",
    slug: "miami",
    state: "florida",
    stateName: "Florida",
    population: 442241,
    medianAge: 40.2,
    medianIncome: 44268,
    retirementPct: 27.3,
    majorEmployers: ["Baptist Health South Florida", "University of Miami", "Royal Caribbean", "Carnival Corporation", "Lennar"],
  },
  {
    name: "Naples",
    slug: "naples",
    state: "florida",
    stateName: "Florida",
    population: 22088,
    medianAge: 65.4,
    medianIncome: 78560,
    retirementPct: 58.6,
    majorEmployers: ["NCH Healthcare System", "Arthrex", "ASG Technologies", "Ritz-Carlton Naples", "Collier County Schools"],
  },
  {
    name: "Orlando",
    slug: "orlando",
    state: "florida",
    stateName: "Florida",
    population: 307573,
    medianAge: 34.1,
    medianIncome: 51757,
    retirementPct: 20.8,
    majorEmployers: ["Walt Disney World", "AdventHealth", "Lockheed Martin", "Universal Orlando", "Siemens Energy"],
  },
  {
    name: "Sarasota",
    slug: "sarasota",
    state: "florida",
    stateName: "Florida",
    population: 57738,
    medianAge: 49.5,
    medianIncome: 53580,
    retirementPct: 42.5,
    majorEmployers: ["Sarasota Memorial Health", "PGT Innovations", "Boar's Head", "FCCI Insurance", "Tervis Tumbler"],
  },
  {
    name: "St. Petersburg",
    slug: "st-petersburg",
    state: "florida",
    stateName: "Florida",
    population: 258308,
    medianAge: 42.0,
    medianIncome: 53650,
    retirementPct: 30.1,
    majorEmployers: ["Johns Hopkins All Children's Hospital", "Raymond James Financial", "Jabil", "HSN", "Duke Energy Florida"],
  },
  {
    name: "Tampa",
    slug: "tampa",
    state: "florida",
    stateName: "Florida",
    population: 384959,
    medianAge: 36.1,
    medianIncome: 53833,
    retirementPct: 24.5,
    majorEmployers: ["BayCare Health System", "USAA", "Citigroup", "Moffitt Cancer Center", "MacDill Air Force Base"],
  },
  {
    name: "The Villages",
    slug: "the-villages",
    state: "florida",
    stateName: "Florida",
    population: 79077,
    medianAge: 72.4,
    medianIncome: 52130,
    retirementPct: 83.7,
    majorEmployers: ["The Villages Health", "Rohan Recreation", "Sumter County Schools", "UF Health The Villages Hospital", "Walmart"],
  },
  // Georgia
  {
    name: "Atlanta",
    slug: "atlanta",
    state: "georgia",
    stateName: "Georgia",
    population: 498715,
    medianAge: 33.9,
    medianIncome: 59948,
    retirementPct: 20.5,
    majorEmployers: ["Emory Healthcare", "Delta Air Lines", "The Home Depot", "UPS", "Coca-Cola"],
  },
  {
    name: "Savannah",
    slug: "savannah",
    state: "georgia",
    stateName: "Georgia",
    population: 147780,
    medianAge: 33.5,
    medianIncome: 42560,
    retirementPct: 24.3,
    majorEmployers: ["Memorial Health University Medical Center", "Gulfstream Aerospace", "St. Joseph's Hospital", "Hunter Army Airfield", "JCB North America"],
  },
  // Hawaii
  {
    name: "Honolulu",
    slug: "honolulu",
    state: "hawaii",
    stateName: "Hawaii",
    population: 350964,
    medianAge: 41.3,
    medianIncome: 63540,
    retirementPct: 29.1,
    majorEmployers: ["Joint Base Pearl Harbor-Hickam", "Queen's Medical Center", "Hawaiian Airlines", "Bank of Hawaii", "Kaiser Permanente Hawaii"],
  },
  // Idaho
  {
    name: "Boise",
    slug: "boise",
    state: "idaho",
    stateName: "Idaho",
    population: 235684,
    medianAge: 36.6,
    medianIncome: 57346,
    retirementPct: 24.0,
    majorEmployers: ["Micron Technology", "St. Luke's Health System", "Albertsons", "Boise State University", "HP Inc"],
  },
  // Illinois
  {
    name: "Chicago",
    slug: "chicago",
    state: "illinois",
    stateName: "Illinois",
    population: 2693976,
    medianAge: 34.8,
    medianIncome: 58247,
    retirementPct: 22.6,
    majorEmployers: ["Advocate Aurora Health", "Boeing", "United Airlines", "Abbott Laboratories", "Walgreens"],
  },
  {
    name: "Naperville",
    slug: "naperville",
    state: "illinois",
    stateName: "Illinois",
    population: 149540,
    medianAge: 39.8,
    medianIncome: 123990,
    retirementPct: 26.3,
    majorEmployers: ["Edward-Elmhurst Health", "Nokia", "Nalco Water", "Calamos Investments", "Nicor Gas"],
  },
  // Indiana
  {
    name: "Indianapolis",
    slug: "indianapolis",
    state: "indiana",
    stateName: "Indiana",
    population: 887642,
    medianAge: 34.4,
    medianIncome: 47873,
    retirementPct: 23.1,
    majorEmployers: ["IU Health", "Eli Lilly", "Anthem", "Rolls-Royce", "Roche Diagnostics"],
  },
  // Iowa
  {
    name: "Des Moines",
    slug: "des-moines",
    state: "iowa",
    stateName: "Iowa",
    population: 214133,
    medianAge: 34.0,
    medianIncome: 52251,
    retirementPct: 22.7,
    majorEmployers: ["Principal Financial Group", "Wells Fargo", "Mercy Medical Center", "UnityPoint Health", "EMC Insurance"],
  },
  // Kansas
  {
    name: "Wichita",
    slug: "wichita",
    state: "kansas",
    stateName: "Kansas",
    population: 397532,
    medianAge: 34.2,
    medianIncome: 50060,
    retirementPct: 23.8,
    majorEmployers: ["Spirit AeroSystems", "Textron Aviation", "Koch Industries", "Via Christi Health", "Bombardier Learjet"],
  },
  // Kentucky
  {
    name: "Louisville",
    slug: "louisville",
    state: "kentucky",
    stateName: "Kentucky",
    population: 633045,
    medianAge: 37.8,
    medianIncome: 52237,
    retirementPct: 26.0,
    majorEmployers: ["UPS Worldport", "Humana", "Norton Healthcare", "Ford Motor Company", "GE Appliances"],
  },
  // Louisiana
  {
    name: "New Orleans",
    slug: "new-orleans",
    state: "louisiana",
    stateName: "Louisiana",
    population: 383997,
    medianAge: 37.1,
    medianIncome: 41604,
    retirementPct: 25.4,
    majorEmployers: ["Ochsner Health", "Tulane University", "Entergy", "Lockheed Martin", "LCMC Health"],
  },
  // Maine
  {
    name: "Portland",
    slug: "portland",
    state: "maine",
    stateName: "Maine",
    population: 68408,
    medianAge: 37.9,
    medianIncome: 55470,
    retirementPct: 26.8,
    majorEmployers: ["Maine Medical Center", "IDEXX Laboratories", "WEX Inc", "L.L.Bean", "Unum Group"],
  },
  // Maryland
  {
    name: "Baltimore",
    slug: "baltimore",
    state: "maryland",
    stateName: "Maryland",
    population: 585708,
    medianAge: 35.4,
    medianIncome: 50177,
    retirementPct: 25.2,
    majorEmployers: ["Johns Hopkins University", "Under Armour", "T. Rowe Price", "Legg Mason", "Constellation Energy"],
  },
  // Massachusetts
  {
    name: "Boston",
    slug: "boston",
    state: "massachusetts",
    stateName: "Massachusetts",
    population: 675647,
    medianAge: 32.8,
    medianIncome: 71115,
    retirementPct: 21.8,
    majorEmployers: ["Massachusetts General Hospital", "Fidelity Investments", "Liberty Mutual", "State Street Corporation", "Raytheon Technologies"],
  },
  {
    name: "Cape Cod",
    slug: "cape-cod",
    state: "massachusetts",
    stateName: "Massachusetts",
    population: 228996,
    medianAge: 52.1,
    medianIncome: 64730,
    retirementPct: 43.2,
    majorEmployers: ["Cape Cod Healthcare", "Joint Base Cape Cod", "Southcoast Health", "Cape Cod Community College", "Ocean Spray"],
  },
  // Michigan
  {
    name: "Detroit",
    slug: "detroit",
    state: "michigan",
    stateName: "Michigan",
    population: 639111,
    medianAge: 34.7,
    medianIncome: 31283,
    retirementPct: 24.5,
    majorEmployers: ["General Motors", "Ford Motor Company", "Stellantis", "Henry Ford Health", "Beaumont Health"],
  },
  {
    name: "Grand Rapids",
    slug: "grand-rapids",
    state: "michigan",
    stateName: "Michigan",
    population: 198917,
    medianAge: 31.9,
    medianIncome: 48710,
    retirementPct: 21.6,
    majorEmployers: ["Spectrum Health", "Amway", "Meijer", "Steelcase", "Mercy Health"],
  },
  // Minnesota
  {
    name: "Minneapolis",
    slug: "minneapolis",
    state: "minnesota",
    stateName: "Minnesota",
    population: 429954,
    medianAge: 33.0,
    medianIncome: 60562,
    retirementPct: 20.4,
    majorEmployers: ["UnitedHealth Group", "Target Corporation", "US Bancorp", "3M", "Medtronic"],
  },
  // Mississippi
  {
    name: "Jackson",
    slug: "jackson",
    state: "mississippi",
    stateName: "Mississippi",
    population: 153701,
    medianAge: 33.5,
    medianIncome: 36528,
    retirementPct: 24.1,
    majorEmployers: ["University of Mississippi Medical Center", "Nissan", "Sanderson Farms", "AT&T", "Baptist Health Systems"],
  },
  // Missouri
  {
    name: "Kansas City",
    slug: "kansas-city",
    state: "missouri",
    stateName: "Missouri",
    population: 508090,
    medianAge: 35.2,
    medianIncome: 52432,
    retirementPct: 23.5,
    majorEmployers: ["Cerner Corporation", "Hallmark Cards", "Sprint", "Burns & McDonnell", "Saint Luke's Health System"],
  },
  {
    name: "St. Louis",
    slug: "st-louis",
    state: "missouri",
    stateName: "Missouri",
    population: 301578,
    medianAge: 35.8,
    medianIncome: 43896,
    retirementPct: 25.7,
    majorEmployers: ["BJC HealthCare", "Emerson Electric", "Edward Jones", "Centene Corporation", "Anheuser-Busch"],
  },
  // Montana
  {
    name: "Billings",
    slug: "billings",
    state: "montana",
    stateName: "Montana",
    population: 119602,
    medianAge: 37.6,
    medianIncome: 54870,
    retirementPct: 26.9,
    majorEmployers: ["Billings Clinic", "St. Vincent Healthcare", "ExxonMobil", "First Interstate BancSystem", "Stillwater Mining"],
  },
  // Nebraska
  {
    name: "Omaha",
    slug: "omaha",
    state: "nebraska",
    stateName: "Nebraska",
    population: 486051,
    medianAge: 34.7,
    medianIncome: 55551,
    retirementPct: 23.4,
    majorEmployers: ["Berkshire Hathaway", "Mutual of Omaha", "Union Pacific", "ConAgra Brands", "Peter Kiewit Sons'"],
  },
  // Nevada
  {
    name: "Henderson",
    slug: "henderson",
    state: "nevada",
    stateName: "Nevada",
    population: 320189,
    medianAge: 41.2,
    medianIncome: 67808,
    retirementPct: 30.6,
    majorEmployers: ["St. Rose Dominican Hospitals", "Station Casinos", "Barrick Gold", "Nevada State College", "City of Henderson"],
  },
  {
    name: "Las Vegas",
    slug: "las-vegas",
    state: "nevada",
    stateName: "Nevada",
    population: 641903,
    medianAge: 38.1,
    medianIncome: 54143,
    retirementPct: 26.4,
    majorEmployers: ["MGM Resorts", "Wynn Resorts", "Caesars Entertainment", "Las Vegas Sands", "Southwest Airlines"],
  },
  {
    name: "Reno",
    slug: "reno",
    state: "nevada",
    stateName: "Nevada",
    population: 264165,
    medianAge: 37.3,
    medianIncome: 56848,
    retirementPct: 25.1,
    majorEmployers: ["Renown Health", "University of Nevada Reno", "IGT", "Sierra Nevada Corporation", "Panasonic Energy"],
  },
  // New Hampshire
  {
    name: "Manchester",
    slug: "manchester",
    state: "new-hampshire",
    stateName: "New Hampshire",
    population: 115644,
    medianAge: 36.8,
    medianIncome: 60821,
    retirementPct: 25.3,
    majorEmployers: ["Elliot Health System", "Catholic Medical Center", "DEKA Research", "Fidelity Investments", "BAE Systems"],
  },
  // New Jersey
  {
    name: "Jersey City",
    slug: "jersey-city",
    state: "new-jersey",
    stateName: "New Jersey",
    population: 262075,
    medianAge: 34.2,
    medianIncome: 72210,
    retirementPct: 20.9,
    majorEmployers: ["Goldman Sachs", "JPMorgan Chase", "Citigroup", "Liberty Health", "RWJBarnabas Health"],
  },
  {
    name: "Toms River",
    slug: "toms-river",
    state: "new-jersey",
    stateName: "New Jersey",
    population: 95438,
    medianAge: 44.7,
    medianIncome: 66210,
    retirementPct: 34.5,
    majorEmployers: ["Community Medical Center", "Ocean County Government", "Ciba Specialty Chemicals", "Ocean County College", "Meridian Health"],
  },
  // New Mexico
  {
    name: "Albuquerque",
    slug: "albuquerque",
    state: "new-mexico",
    stateName: "New Mexico",
    population: 564559,
    medianAge: 36.7,
    medianIncome: 52911,
    retirementPct: 25.6,
    majorEmployers: ["Sandia National Laboratories", "Kirtland Air Force Base", "Presbyterian Healthcare", "University of New Mexico", "Intel"],
  },
  {
    name: "Santa Fe",
    slug: "santa-fe",
    state: "new-mexico",
    stateName: "New Mexico",
    population: 87505,
    medianAge: 46.3,
    medianIncome: 55860,
    retirementPct: 36.8,
    majorEmployers: ["State of New Mexico", "Christus St. Vincent Regional Medical Center", "Los Alamos National Laboratory", "Santa Fe Public Schools", "Santa Fe Community College"],
  },
  // New York
  {
    name: "Buffalo",
    slug: "buffalo",
    state: "new-york",
    stateName: "New York",
    population: 278349,
    medianAge: 33.7,
    medianIncome: 37354,
    retirementPct: 24.9,
    majorEmployers: ["Kaleida Health", "M&T Bank", "Catholic Health", "Moog Inc", "Rich Products"],
  },
  {
    name: "New York City",
    slug: "new-york-city",
    state: "new-york",
    stateName: "New York",
    population: 8336817,
    medianAge: 37.2,
    medianIncome: 63998,
    retirementPct: 23.7,
    majorEmployers: ["NYC Health + Hospitals", "JPMorgan Chase", "Citigroup", "Verizon", "Pfizer"],
  },
  // North Carolina
  {
    name: "Asheville",
    slug: "asheville",
    state: "north-carolina",
    stateName: "North Carolina",
    population: 94067,
    medianAge: 40.7,
    medianIncome: 48672,
    retirementPct: 30.5,
    majorEmployers: ["Mission Health", "Ingles Markets", "BorgWarner", "Eaton Corporation", "Biltmore Company"],
  },
  {
    name: "Charlotte",
    slug: "charlotte",
    state: "north-carolina",
    stateName: "North Carolina",
    population: 874579,
    medianAge: 34.4,
    medianIncome: 62817,
    retirementPct: 21.2,
    majorEmployers: ["Atrium Health", "Bank of America", "Lowe's", "Honeywell", "Duke Energy"],
  },
  {
    name: "Raleigh",
    slug: "raleigh",
    state: "north-carolina",
    stateName: "North Carolina",
    population: 467665,
    medianAge: 34.0,
    medianIncome: 63891,
    retirementPct: 20.6,
    majorEmployers: ["WakeMed Health", "Cisco Systems", "IBM", "SAS Institute", "Duke Energy"],
  },
  {
    name: "Wilmington",
    slug: "wilmington",
    state: "north-carolina",
    stateName: "North Carolina",
    population: 122607,
    medianAge: 38.7,
    medianIncome: 47384,
    retirementPct: 29.4,
    majorEmployers: ["New Hanover Regional Medical Center", "GE Hitachi Nuclear Energy", "PPD Inc", "Corning", "Live Oak Bank"],
  },
  // North Dakota
  {
    name: "Fargo",
    slug: "fargo",
    state: "north-dakota",
    stateName: "North Dakota",
    population: 125990,
    medianAge: 32.0,
    medianIncome: 48810,
    retirementPct: 20.1,
    majorEmployers: ["Sanford Health", "Essentia Health", "Microsoft", "Bobcat Company", "Blue Cross Blue Shield of ND"],
  },
  // Ohio
  {
    name: "Cincinnati",
    slug: "cincinnati",
    state: "ohio",
    stateName: "Ohio",
    population: 309317,
    medianAge: 33.1,
    medianIncome: 40640,
    retirementPct: 24.3,
    majorEmployers: ["Procter & Gamble", "Kroger", "Cincinnati Children's Hospital", "Fifth Third Bancorp", "GE Aviation"],
  },
  {
    name: "Cleveland",
    slug: "cleveland",
    state: "ohio",
    stateName: "Ohio",
    population: 372624,
    medianAge: 36.2,
    medianIncome: 30907,
    retirementPct: 26.8,
    majorEmployers: ["Cleveland Clinic", "University Hospitals", "KeyCorp", "Progressive Insurance", "Sherwin-Williams"],
  },
  {
    name: "Columbus",
    slug: "columbus",
    state: "ohio",
    stateName: "Ohio",
    population: 905748,
    medianAge: 32.5,
    medianIncome: 53745,
    retirementPct: 20.7,
    majorEmployers: ["Ohio State University", "Nationwide Insurance", "Cardinal Health", "L Brands", "Huntington Bancshares"],
  },
  {
    name: "Dayton",
    slug: "dayton",
    state: "ohio",
    stateName: "Ohio",
    population: 137644,
    medianAge: 34.5,
    medianIncome: 32540,
    retirementPct: 26.1,
    majorEmployers: ["Wright-Patterson Air Force Base", "Premier Health", "CareSource", "LexisNexis", "Dayton Children's Hospital"],
  },
  // Oklahoma
  {
    name: "Oklahoma City",
    slug: "oklahoma-city",
    state: "oklahoma",
    stateName: "Oklahoma",
    population: 681054,
    medianAge: 34.6,
    medianIncome: 54034,
    retirementPct: 23.4,
    majorEmployers: ["Tinker Air Force Base", "INTEGRIS Health", "Devon Energy", "Paycom", "Chesapeake Energy"],
  },
  // Oregon
  {
    name: "Portland",
    slug: "portland",
    state: "oregon",
    stateName: "Oregon",
    population: 652503,
    medianAge: 37.0,
    medianIncome: 65740,
    retirementPct: 23.8,
    majorEmployers: ["OHSU", "Intel", "Nike", "Providence Health", "Daimler Trucks North America"],
  },
  // Pennsylvania
  {
    name: "Philadelphia",
    slug: "philadelphia",
    state: "pennsylvania",
    stateName: "Pennsylvania",
    population: 1584064,
    medianAge: 34.3,
    medianIncome: 45927,
    retirementPct: 24.6,
    majorEmployers: ["University of Pennsylvania Health", "Comcast", "Jefferson Health", "Independence Health Group", "Aramark"],
  },
  {
    name: "Pittsburgh",
    slug: "pittsburgh",
    state: "pennsylvania",
    stateName: "Pennsylvania",
    population: 302971,
    medianAge: 33.5,
    medianIncome: 48711,
    retirementPct: 25.4,
    majorEmployers: ["UPMC", "PNC Financial", "US Steel", "PPG Industries", "BNY Mellon"],
  },
  // Rhode Island
  {
    name: "Providence",
    slug: "providence",
    state: "rhode-island",
    stateName: "Rhode Island",
    population: 190934,
    medianAge: 31.0,
    medianIncome: 42658,
    retirementPct: 22.8,
    majorEmployers: ["Lifespan", "CVS Health", "Citizens Financial Group", "Brown University", "Care New England"],
  },
  // South Carolina
  {
    name: "Charleston",
    slug: "charleston",
    state: "south-carolina",
    stateName: "South Carolina",
    population: 150227,
    medianAge: 35.2,
    medianIncome: 62367,
    retirementPct: 26.1,
    majorEmployers: ["MUSC Health", "Boeing", "Joint Base Charleston", "Roper St. Francis Healthcare", "Blackbaud"],
  },
  {
    name: "Hilton Head Island",
    slug: "hilton-head-island",
    state: "south-carolina",
    stateName: "South Carolina",
    population: 40000,
    medianAge: 55.3,
    medianIncome: 73510,
    retirementPct: 48.2,
    majorEmployers: ["Hilton Head Hospital", "Marriott Vacations", "Sea Pines Resort", "Beaufort County Schools", "Omni Hilton Head"],
  },
  {
    name: "Myrtle Beach",
    slug: "myrtle-beach",
    state: "south-carolina",
    stateName: "South Carolina",
    population: 35682,
    medianAge: 42.1,
    medianIncome: 39780,
    retirementPct: 33.7,
    majorEmployers: ["Grand Strand Medical Center", "Burroughs & Chapin", "Coastal Carolina University", "City of Myrtle Beach", "AVX Corporation"],
  },
  // South Dakota
  {
    name: "Sioux Falls",
    slug: "sioux-falls",
    state: "south-dakota",
    stateName: "South Dakota",
    population: 192517,
    medianAge: 34.5,
    medianIncome: 57380,
    retirementPct: 23.2,
    majorEmployers: ["Sanford Health", "Avera Health", "Citibank", "Wells Fargo", "Smithfield Foods"],
  },
  // Tennessee
  {
    name: "Knoxville",
    slug: "knoxville",
    state: "tennessee",
    stateName: "Tennessee",
    population: 190740,
    medianAge: 35.2,
    medianIncome: 39205,
    retirementPct: 25.7,
    majorEmployers: ["University of Tennessee", "Covenant Health", "Pilot Flying J", "Tennessee Valley Authority", "Regal Entertainment"],
  },
  {
    name: "Memphis",
    slug: "memphis",
    state: "tennessee",
    stateName: "Tennessee",
    population: 633104,
    medianAge: 34.0,
    medianIncome: 39108,
    retirementPct: 23.5,
    majorEmployers: ["FedEx", "St. Jude Children's Research Hospital", "International Paper", "AutoZone", "ServiceMaster"],
  },
  {
    name: "Nashville",
    slug: "nashville",
    state: "tennessee",
    stateName: "Tennessee",
    population: 689447,
    medianAge: 34.3,
    medianIncome: 55873,
    retirementPct: 22.3,
    majorEmployers: ["HCA Healthcare", "Vanderbilt University Medical Center", "Nissan", "Bridgestone Americas", "Dollar General"],
  },
  // Texas
  {
    name: "Austin",
    slug: "austin",
    state: "texas",
    stateName: "Texas",
    population: 978908,
    medianAge: 33.9,
    medianIncome: 71576,
    retirementPct: 18.9,
    majorEmployers: ["Dell Technologies", "University of Texas", "Apple", "Samsung", "Ascension Seton"],
  },
  {
    name: "Dallas",
    slug: "dallas",
    state: "texas",
    stateName: "Texas",
    population: 1304379,
    medianAge: 33.5,
    medianIncome: 52580,
    retirementPct: 21.0,
    majorEmployers: ["Baylor Scott & White Health", "AT&T", "Southwest Airlines", "Texas Instruments", "ExxonMobil"],
  },
  {
    name: "Fort Worth",
    slug: "fort-worth",
    state: "texas",
    stateName: "Texas",
    population: 918915,
    medianAge: 33.1,
    medianIncome: 58313,
    retirementPct: 20.5,
    majorEmployers: ["Lockheed Martin", "American Airlines", "BNSF Railway", "Bell Textron", "JPS Health Network"],
  },
  {
    name: "Houston",
    slug: "houston",
    state: "texas",
    stateName: "Texas",
    population: 2304580,
    medianAge: 33.8,
    medianIncome: 52338,
    retirementPct: 20.7,
    majorEmployers: ["MD Anderson Cancer Center", "ExxonMobil", "Shell", "Memorial Hermann Health", "NASA Johnson Space Center"],
  },
  {
    name: "San Antonio",
    slug: "san-antonio",
    state: "texas",
    stateName: "Texas",
    population: 1547253,
    medianAge: 33.8,
    medianIncome: 52455,
    retirementPct: 23.6,
    majorEmployers: ["USAA", "Joint Base San Antonio", "H-E-B", "Methodist Healthcare", "Valero Energy"],
  },
  // Utah
  {
    name: "Salt Lake City",
    slug: "salt-lake-city",
    state: "utah",
    stateName: "Utah",
    population: 199723,
    medianAge: 33.3,
    medianIncome: 56370,
    retirementPct: 20.1,
    majorEmployers: ["Intermountain Healthcare", "University of Utah", "Goldman Sachs", "Delta Air Lines", "Zions Bancorporation"],
  },
  // Vermont
  {
    name: "Burlington",
    slug: "burlington",
    state: "vermont",
    stateName: "Vermont",
    population: 44743,
    medianAge: 34.2,
    medianIncome: 52120,
    retirementPct: 24.5,
    majorEmployers: ["University of Vermont Medical Center", "GlobalFoundries", "Dealer.com", "Ben & Jerry's", "Burton Snowboards"],
  },
  // Virginia
  {
    name: "Norfolk",
    slug: "norfolk",
    state: "virginia",
    stateName: "Virginia",
    population: 238005,
    medianAge: 31.4,
    medianIncome: 47191,
    retirementPct: 22.8,
    majorEmployers: ["Naval Station Norfolk", "Sentara Healthcare", "Norfolk Southern", "Eastern Virginia Medical School", "Dollar Tree"],
  },
  {
    name: "Richmond",
    slug: "richmond",
    state: "virginia",
    stateName: "Virginia",
    population: 226610,
    medianAge: 34.3,
    medianIncome: 47250,
    retirementPct: 24.0,
    majorEmployers: ["VCU Health", "Capital One", "Dominion Energy", "Altria Group", "CarMax"],
  },
  {
    name: "Virginia Beach",
    slug: "virginia-beach",
    state: "virginia",
    stateName: "Virginia",
    population: 449974,
    medianAge: 37.0,
    medianIncome: 76610,
    retirementPct: 26.4,
    majorEmployers: ["Naval Air Station Oceana", "Sentara Healthcare", "GEICO", "Stihl Inc", "Amerigroup"],
  },
  // Washington
  {
    name: "Seattle",
    slug: "seattle",
    state: "washington",
    stateName: "Washington",
    population: 737015,
    medianAge: 35.6,
    medianIncome: 92263,
    retirementPct: 20.2,
    majorEmployers: ["Amazon", "Microsoft", "Boeing", "University of Washington", "Swedish Medical Center"],
  },
  {
    name: "Spokane",
    slug: "spokane",
    state: "washington",
    stateName: "Washington",
    population: 228989,
    medianAge: 35.9,
    medianIncome: 45230,
    retirementPct: 26.3,
    majorEmployers: ["Providence Sacred Heart Medical Center", "Fairchild Air Force Base", "MultiCare Health", "Gonzaga University", "STCU"],
  },
  // West Virginia
  {
    name: "Charleston",
    slug: "charleston",
    state: "west-virginia",
    stateName: "West Virginia",
    population: 48006,
    medianAge: 41.7,
    medianIncome: 42190,
    retirementPct: 31.4,
    majorEmployers: ["CAMC Health System", "WVU Medicine", "Dow Chemical", "State of West Virginia", "United Bank"],
  },
  // Wisconsin
  {
    name: "Madison",
    slug: "madison",
    state: "wisconsin",
    stateName: "Wisconsin",
    population: 269840,
    medianAge: 31.5,
    medianIncome: 65332,
    retirementPct: 20.0,
    majorEmployers: ["University of Wisconsin", "Epic Systems", "American Family Insurance", "UW Health", "Exact Sciences"],
  },
  {
    name: "Milwaukee",
    slug: "milwaukee",
    state: "wisconsin",
    stateName: "Wisconsin",
    population: 577222,
    medianAge: 31.8,
    medianIncome: 41838,
    retirementPct: 23.4,
    majorEmployers: ["Aurora Health Care", "Northwestern Mutual", "Rockwell Automation", "Johnson Controls", "Harley-Davidson"],
  },
  // Wyoming
  {
    name: "Cheyenne",
    slug: "cheyenne",
    state: "wyoming",
    stateName: "Wyoming",
    population: 65132,
    medianAge: 36.8,
    medianIncome: 57840,
    retirementPct: 25.7,
    majorEmployers: ["F.E. Warren Air Force Base", "Cheyenne Regional Medical Center", "State of Wyoming", "NCAR", "Sierra Trading Post"],
  },
];

// Helper functions
export function getCitiesByState(stateSlug: string): CityData[] {
  return CITIES.filter((c) => c.state === stateSlug);
}

export function getCityBySlug(
  stateSlug: string,
  citySlug: string
): CityData | undefined {
  return CITIES.find((c) => c.state === stateSlug && c.slug === citySlug);
}

export function getAllCitySlugs(): { state: string; city: string }[] {
  return CITIES.map((c) => ({ state: c.state, city: c.slug }));
}
