export const US_STATES = [
    { name: "Alabama", slug: "alabama", taxFriendly: true },
    { name: "Alaska", slug: "alaska", taxFriendly: true },
    { name: "Arizona", slug: "arizona", taxFriendly: true },
    { name: "Arkansas", slug: "arkansas", taxFriendly: true },
    { name: "California", slug: "california", taxFriendly: false },
    { name: "Colorado", slug: "colorado", taxFriendly: true },
    { name: "Connecticut", slug: "connecticut", taxFriendly: false },
    { name: "Delaware", slug: "delaware", taxFriendly: true },
    { name: "Florida", slug: "florida", taxFriendly: true },
    { name: "Georgia", slug: "georgia", taxFriendly: true },
    { name: "Hawaii", slug: "hawaii", taxFriendly: false },
    { name: "Idaho", slug: "idaho", taxFriendly: true },
    { name: "Illinois", slug: "illinois", taxFriendly: true },
    { name: "Indiana", slug: "indiana", taxFriendly: true },
    { name: "Iowa", slug: "iowa", taxFriendly: true },
    { name: "Kansas", slug: "kansas", taxFriendly: true },
    { name: "Kentucky", slug: "kentucky", taxFriendly: false },
    { name: "Louisiana", slug: "louisiana", taxFriendly: true },
    { name: "Maine", slug: "maine", taxFriendly: false },
    { name: "Maryland", slug: "maryland", taxFriendly: false },
    { name: "Massachusetts", slug: "massachusetts", taxFriendly: false },
    { name: "Michigan", slug: "michigan", taxFriendly: true },
    { name: "Minnesota", slug: "minnesota", taxFriendly: true },
    { name: "Mississippi", slug: "mississippi", taxFriendly: false },
    { name: "Missouri", slug: "missouri", taxFriendly: true },
    { name: "Montana", slug: "montana", taxFriendly: true },
    { name: "Nebraska", slug: "nebraska", taxFriendly: true },
    { name: "Nevada", slug: "nevada", taxFriendly: false },
    { name: "New Hampshire", slug: "new-hampshire", taxFriendly: true },
    { name: "New Jersey", slug: "new-jersey", taxFriendly: false },
    { name: "New Mexico", slug: "new-mexico", taxFriendly: false },
    { name: "New York", slug: "new-york", taxFriendly: true },
    { name: "North Carolina", slug: "north-carolina", taxFriendly: true },
    { name: "North Dakota", slug: "north-dakota", taxFriendly: true },
    { name: "Ohio", slug: "ohio", taxFriendly: true },
    { name: "Oklahoma", slug: "oklahoma", taxFriendly: true },
    { name: "Oregon", slug: "oregon", taxFriendly: true },
    { name: "Pennsylvania", slug: "pennsylvania", taxFriendly: true },
    { name: "Rhode Island", slug: "rhode-island", taxFriendly: false },
    { name: "South Carolina", slug: "south-carolina", taxFriendly: true },
    { name: "South Dakota", slug: "south-dakota", taxFriendly: true },
    { name: "Tennessee", slug: "tennessee", taxFriendly: false },
    { name: "Texas", slug: "texas", taxFriendly: true },
    { name: "Utah", slug: "utah", taxFriendly: true },
    { name: "Vermont", slug: "vermont", taxFriendly: false },
    { name: "Virginia", slug: "virginia", taxFriendly: true },
    { name: "Washington", slug: "washington", taxFriendly: false },
    { name: "West Virginia", slug: "west-virginia", taxFriendly: false },
    { name: "Wisconsin", slug: "wisconsin", taxFriendly: false },
    { name: "Wyoming", slug: "wyoming", taxFriendly: true }
];
